import FavList from '@/components/Pages/FavList'
import OrdersList from '@/components/Pages/OrdersList'
import { useStore } from '@/store/globalStore'
import type { Metadata } from 'next'
import React from 'react'

export const metadata: Metadata = {
  title: 'Триал-Спорт Dashboard',
  description: 'Generated by create next app',
}

const FavoritesPage = () => {
  return (
    <div className="py-12">
      <div className="max-w-7xl mx-auto sm:px-6 lg:px-8">
        <FavList />
      </div>
    </div>
  )
}

export default FavoritesPage
