import FavList from '@/components/Pages/FavList'
import OrdersList from '@/components/Pages/OrdersList'
import { useStore } from '@/store/globalStore'
import type { Metadata } from 'next'
import React from 'react'

export const metadata: Metadata = {
  title: 'Триал-Спорт Dashboard',
  description: 'Generated by create next app',
}

const DashboardPageX = () => {
  return (
    <div className="py-12">
      <div className="max-w-7xl mx-auto sm:px-6 lg:px-8">
        <div className="bg-white overflow-hidden shadow-sm sm:rounded-lg">
          <div className="p-6 bg-white border-b border-gray-200">
            {`You're logged in!`}
          </div>
        </div>
        <OrdersList />
        <FavList />
      </div>
    </div>
  )
}

export default DashboardPageX
